# Generated by Django 6.0.7 on 2026-07-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, help_text='Used for license expiry reminder emails.', max_length=254),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
