# Generated by Django 6.0.7 on 2026-07-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_email_driver_last_reminder_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_expiry',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('off_duty', 'Off Duty'), ('suspended', 'Suspended')], db_index=True, default='available', max_length=20),
        ),
    ]
