# Generated by Django 6.0.7 on 2026-07-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('van', 'Van'), ('truck', 'Truck'), ('bus', 'Bus'), ('car', 'Car'), ('motorcycle', 'Motorcycle')], max_length=50)),
                ('max_load_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odometer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('in_shop', 'In Shop'), ('retired', 'Retired')], default='available', max_length=20)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
