# Generated by Django 6.0.7 on 2026-07-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicledocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='region',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('in_shop', 'In Shop'), ('retired', 'Retired')], db_index=True, default='available', max_length=20),
        ),
    ]
